In [25]:
import numpy as np
grades=np.array([
    [20,20,20,20,20],
    [15,17,16,16,16],
    [18,19,19,20,19],
    [14,13,14,15,14],
    [17,18,18,18,18],
    [12,12,13,13,13],
    [15,16,15,15,14],
    [18,18,18,19,18],
    [16,17,16,17,16],
    [13,13,14,14,14],
    
])
class_average=np.mean(grades)
print(class_average)

student_ave=np.mean(grades, axis=1)
print("student averages : ", student_ave)

student_ave=np.mean(grades, axis=0)
print("student averages_lesson : ", student_ave)

16.26
student averages :  [20.  16.  19.  14.  17.8 12.6 15.  18.2 16.4 13.6]
student averages_lesson :  [15.8 16.3 16.3 16.7 16.2]


In [5]:
top_student=np.argsort(student_ave)[-3:][::-1]
print(top_student)
print("top student : ", top_student +1)

[0 2 7]
top student :  [1 3 8]


In [7]:
subject_averages=np.mean(grades,axis=0)
print("subject averages:" , subject_averages)

top_subject=np.argmax(subject_averages)
print("top subject :" , top_subject)

subjects=["math","physics","biologhy","english","history"]
print(f"top subject is {subjects[top_subject]}")

subject averages: [15.8 16.3 16.3 16.7 16.2]
top subject : 3
top subject is english


In [9]:
variances=np.var(grades,axis=0)
print(variances)
stds=np.std(grades,axis=0)
print(stds)

[5.56 6.81 5.01 5.61 5.36]
[2.35796522 2.60959767 2.23830293 2.36854386 2.31516738]


In [13]:
top_grades=np.all(grades>17,axis=1)
print(top_grades)
counts=np.sum(top_grades)
print(counts)


[ True False  True False False False False  True False False]
3
